/*for 1st case (negative)*/
CREATE TABLE LOG_JOB_TEST15
(ID_JOB INTEGER, CHANNEL_ID VARCHAR(255), JOBNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT,LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(15));
/*for 1st case (positive)*/
CREATE TABLE LOG_JOB_TEST15_CLOB
(ID_JOB INTEGER, CHANNEL_ID CLOB, JOBNAME VARCHAR(255), STATUS CLOB, LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT,LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD CLOB);
/*for 2nd case*/
CREATE TABLE LOG_JOB_TEST255
(ID_JOB INTEGER, CHANNEL_ID VARCHAR(255), JOBNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT,LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(255));
/* for log table defined inside transaction */
CREATE TABLE LOG_TRANS_TEST15 ( ID_BATCH INTEGER, CHANNEL_ID VARCHAR(255), TRANSNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT, LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(15));
/* for log transformation */
CREATE TABLE LOG_TRANS_TEST2000 (ID_BATCH INTEGER, CHANNEL_ID VARCHAR(255), TRANSNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT, LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(2000));