# https://github.com/jenkinsci/docker/blob/master/README.md
FROM jenkins/jenkins:lts-alpine

USER root

ENV CREDENTIALS_ID github-buildguy
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# maven-surefire-plugin fails on Docker and Alpine, the version 2.20.1 changed how the plugin interacts with processes
# workaround is to install procps
RUN apk --no-cache add --update procps fontconfig

# adding dynamic ELFs required by PhantomJS, and other glibc dependent apps like java
ADD alpine/tools/dockerized-phantomjs.tgz /

USER jenkins

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

COPY bootstrap /usr/share/jenkins/ref/init.groovy.d/

HEALTHCHECK --interval=30s --timeout=10s --retries=3 CMD curl --fail http://localhost:8080 || exit 1