com.pentaho|pdi=BASE_VERSION
com.pentaho|pentaho-kettle-utilities=BASE_VERSION
com.pentaho|kettle-ui-swt=BASE_VERSION
com.pentaho|pdi-plugins=BASE_VERSION
com.pentaho|yaml-input=BASE_VERSION
com.pentaho|yaml-input-plugins-ui=BASE_VERSIONcom.pentaho|aggregate-rows=BASE_VERSION
com.pentaho|aggregate-rows-assemblies=BASE_VERSION
com.pentaho|aggregate-rows-core=BASE_VERSION
com.pentaho|aggregate-rows-plugin=BASE_VERSION
com.pentaho|avro-format=BASE_VERSION
com.pentaho|avro-format-assemblies=BASE_VERSION
com.pentaho|connected-to-repository=BASE_VERSION
com.pentaho|connected-to-repository-assemblies=BASE_VERSION
com.pentaho|connected-to-repository-plugins=BASE_VERSION
com.pentaho|connected-to-repository-plugins-impl=BASE_VERSION
com.pentaho|connected-to-repository-plugins-ui=BASE_VERSION
com.pentaho|connections=BASE_VERSION
com.pentaho|connections-assemblies=BASE_VERSION
com.pentaho|connections-plugin=BASE_VERSION
com.pentaho|connections-ui=BASE_VERSION
com.pentaho|core-ui=BASE_VERSION
com.pentaho|credit-card-validator=BASE_VERSION
com.pentaho|credit-card-validator-assemblies=BASE_VERSION
com.pentaho|credit-card-validator-plugins=BASE_VERSION
com.pentaho|credit-card-validator-plugins-impl=BASE_VERSION
com.pentaho|credit-card-validator-plugins-ui=BASE_VERSION
com.pentaho|drools=BASE_VERSION
com.pentaho|drools-assemblies=BASE_VERSION
com.pentaho|dummy=BASE_VERSION
com.pentaho|dummy-assemblies=BASE_VERSION
com.pentaho|edi2xml=BASE_VERSION
com.pentaho|edi2xml-assemblies=BASE_VERSION
com.pentaho|edi2xml-plugins=BASE_VERSION
com.pentaho|edi2xml-plugins-impl=BASE_VERSION
com.pentaho|edi2xml-plugins-ui=BASE_VERSION
com.pentaho|elasticsearch-bulk-insert=BASE_VERSION
com.pentaho|elasticsearch-bulk-insert-assemblies=BASE_VERSION
com.pentaho|elasticsearch-bulk-insert-core=BASE_VERSION
com.pentaho|elasticsearch-bulk-insert-plugin=BASE_VERSION
com.pentaho|email-messages=BASE_VERSION
com.pentaho|email-messages-assemblies=BASE_VERSION
com.pentaho|email-messages-plugins=BASE_VERSION
com.pentaho|email-messages-plugins-impl=BASE_VERSION
com.pentaho|email-messages-plugins-ui=BASE_VERSION
com.pentaho|engine-configuration=BASE_VERSION
com.pentaho|engine-configuration-assemblies=BASE_VERSION
com.pentaho|excel=BASE_VERSION
com.pentaho|excel-assemblies=BASE_VERSION
com.pentaho|excel-plugins=BASE_VERSION
com.pentaho|excel-plugins-core=BASE_VERSION
com.pentaho|export-repository=BASE_VERSION
com.pentaho|export-repository-assemblies=BASE_VERSION
com.pentaho|export-repository-plugins=BASE_VERSION
com.pentaho|export-repository-plugins-impl=BASE_VERSION
com.pentaho|export-repository-plugins-ui=BASE_VERSION
com.pentaho|file-open-save-new=BASE_VERSION
com.pentaho|file-open-save-new-api=BASE_VERSION
com.pentaho|file-open-save-new-assemblies=BASE_VERSION
com.pentaho|file-open-save-new-core=BASE_VERSION
com.pentaho|file-open-save-new-plugin=BASE_VERSION
com.pentaho|file-stream=BASE_VERSION
com.pentaho|ftp-delete=BASE_VERSION
com.pentaho|ftp-delete-assemblies=BASE_VERSION
com.pentaho|ftp-delete-plugins=BASE_VERSION
com.pentaho|ftp-delete-plugins-impl=BASE_VERSION
com.pentaho|ftp-delete-plugins-ui=BASE_VERSION
com.pentaho|ftps=BASE_VERSION
com.pentaho|ftps-assemblies=BASE_VERSION
com.pentaho|ftps-plugin=BASE_VERSION
com.pentaho|ftps-plugin-impl=BASE_VERSION
com.pentaho|ftps-plugin-ui=BASE_VERSION
com.pentaho|get-file-sftp=BASE_VERSION
com.pentaho|get-file-sftp-assemblies=BASE_VERSION
com.pentaho|get-file-sftp-plugin=BASE_VERSION
com.pentaho|get-file-sftp-plugin-impl=BASE_VERSION
com.pentaho|get-file-sftp-plugin-ui=BASE_VERSION
com.pentaho|get-file-with-ftp=BASE_VERSION
com.pentaho|get-file-with-ftp-assemblies=BASE_VERSION
com.pentaho|get-file-with-ftp-plugins=BASE_VERSION
com.pentaho|get-file-with-ftp-plugins-impl=BASE_VERSION
com.pentaho|get-file-with-ftp-plugins-ui=BASE_VERSION
com.pentaho|get-previous-row-field=BASE_VERSION
com.pentaho|get-previous-row-field-assemblies=BASE_VERSION
com.pentaho|get-previous-row-field-core=BASE_VERSION
com.pentaho|get-previous-row-field-plugin=BASE_VERSION
com.pentaho|get-repository-names=BASE_VERSION
com.pentaho|get-repository-names-assemblies=BASE_VERSION
com.pentaho|get-repository-names-plugins=BASE_VERSION
com.pentaho|get-repository-names-plugins-impl=BASE_VERSION
com.pentaho|get-repository-names-plugins-ui=BASE_VERSION
com.pentaho|google-analytics=BASE_VERSION
com.pentaho|google-analytics-assemblies=BASE_VERSION
com.pentaho|gp-bulk-loader=BASE_VERSION
com.pentaho|gp-bulk-loader-assemblies=BASE_VERSION
com.pentaho|gp-bulk-loader-core=BASE_VERSION
com.pentaho|gp-bulk-loader-plugin=BASE_VERSION
com.pentaho|gpload=BASE_VERSION
com.pentaho|gpload-assemblies=BASE_VERSION
com.pentaho|hl7=BASE_VERSION
com.pentaho|hl7-assemblies=BASE_VERSION
com.pentaho|importer-utility=BASE_VERSION
com.pentaho|importer-utility-parent-pom=BASE_VERSION
com.pentaho|infobright-bulk-loader=BASE_VERSION
com.pentaho|infobright-bulk-loader-assemblies=BASE_VERSION
com.pentaho|infobright-bulk-loader-plugins=BASE_VERSION
com.pentaho|infobright-bulk-loader-plugins-impl=BASE_VERSION
com.pentaho|infobright-bulk-loader-plugins-ui=BASE_VERSION
com.pentaho|ivw-bulk-loader=BASE_VERSION
com.pentaho|ivw-bulk-loader-assemblies=BASE_VERSION
com.pentaho|ivw-bulk-loader-plugins=BASE_VERSION
com.pentaho|ivw-bulk-loader-plugins-impl=BASE_VERSION
com.pentaho|ivw-bulk-loader-plugins-ui=BASE_VERSION
com.pentaho|json=BASE_VERSION
com.pentaho|json-assemblies=BASE_VERSION
com.pentaho|kafka=BASE_VERSION
com.pentaho|kafka-assemblies=BASE_VERSION
com.pentaho|kafka-plugin-core=BASE_VERSION
com.pentaho|kettle-core=BASE_VERSION
com.pentaho|kettle-dbdialog=BASE_VERSION
com.pentaho|kettle-drools8-core=BASE_VERSION
com.pentaho|kettle-drools8-plugin=BASE_VERSION
com.pentaho|kettle-dummy-plugin=BASE_VERSION
com.pentaho|kettle-dummy-plugin-core=BASE_VERSION
com.pentaho|kettle-engine=BASE_VERSION
com.pentaho|kettle-gpload-plugin=BASE_VERSION
com.pentaho|kettle-gpload-plugin-core=BASE_VERSION
com.pentaho|kettle-hl7-plugin=BASE_VERSION
com.pentaho|kettle-hl7-plugin-core=BASE_VERSION
com.pentaho|kettle-json-plugin=BASE_VERSION
com.pentaho|kettle-json-plugin-core=BASE_VERSION
com.pentaho|kettle-palo-plugin=BASE_VERSION
com.pentaho|kettle-palo-plugin-core=BASE_VERSION
com.pentaho|kettle-repository-locator-platform-plugin=BASE_VERSION
com.pentaho|kettle-repository-locator-plugin=BASE_VERSION
com.pentaho|kettle-repository-locator-spoon-plugin=BASE_VERSION
com.pentaho|kettle-rest-plugin=BASE_VERSION
com.pentaho|kettle-s3csvinput-plugin=BASE_VERSION
com.pentaho|kettle-s3csvinput-plugin-core=BASE_VERSION
com.pentaho|kettle-sap-plugin=BASE_VERSION
com.pentaho|kettle-sap-plugin-core=BASE_VERSION
com.pentaho|kettle-shapefilereader-plugin=BASE_VERSION
com.pentaho|kettle-shapefilereader-plugin-core=BASE_VERSION
com.pentaho|ldap=BASE_VERSION
com.pentaho|ldap-assemblies=BASE_VERSION
com.pentaho|ldap-plugins=BASE_VERSION
com.pentaho|ldap-plugins-impl=BASE_VERSION
com.pentaho|ldap-plugins-ui=BASE_VERSION
com.pentaho|lucid-db-streaming-loader=BASE_VERSION
com.pentaho|lucid-db-streaming-loader-assemblies=BASE_VERSION
com.pentaho|lucid-db-streaming-loader-plugin=BASE_VERSION
com.pentaho|lucid-db-streaming-loader-plugin-core=BASE_VERSION
com.pentaho|mail=BASE_VERSION
com.pentaho|mail-assemblies=BASE_VERSION
com.pentaho|mail-job=BASE_VERSION
com.pentaho|mail-job-assemblies=BASE_VERSION
com.pentaho|mail-job-plugins=BASE_VERSION
com.pentaho|mail-job-plugins-impl=BASE_VERSION
com.pentaho|mail-job-plugins-ui=BASE_VERSION
com.pentaho|mail-plugins=BASE_VERSION
com.pentaho|mail-plugins-impl=BASE_VERSION
com.pentaho|mail-plugins-ui=BASE_VERSION
com.pentaho|mail-validator=BASE_VERSION
com.pentaho|mail-validator-assemblies=BASE_VERSION
com.pentaho|mail-validator-plugins=BASE_VERSION
com.pentaho|mail-validator-plugins-impl=BASE_VERSION
com.pentaho|mail-validator-plugins-ui=BASE_VERSION
com.pentaho|meta-inject=BASE_VERSION
com.pentaho|meta-inject-assemblies=BASE_VERSION
com.pentaho|meta-inject-plugins=BASE_VERSION
com.pentaho|meta-inject-plugins-impl=BASE_VERSION
com.pentaho|metastore-locator=BASE_VERSION
com.pentaho|mondrianinput=BASE_VERSION
com.pentaho|mondrianinput-assemblies=BASE_VERSION
com.pentaho|mondrianinput-impl=BASE_VERSION
com.pentaho|mondrianinput-plugin=BASE_VERSION
com.pentaho|mondrianinput-ui=BASE_VERSION
com.pentaho|monet-db-bulk-loader=BASE_VERSION
com.pentaho|monet-db-bulk-loader-assemblies=BASE_VERSION
com.pentaho|monet-db-bulk-loader-plugins=BASE_VERSION
com.pentaho|monet-db-bulk-loader-plugins-impl=BASE_VERSION
com.pentaho|monet-db-bulk-loader-plugins-ui=BASE_VERSION
com.pentaho|ms-access=BASE_VERSION
com.pentaho|ms-access-assemblies=BASE_VERSION
com.pentaho|ms-access-plugins=BASE_VERSION
com.pentaho|ms-access-plugins-impl=BASE_VERSION
com.pentaho|ms-access-plugins-ui=BASE_VERSION
com.pentaho|msg-box-info=BASE_VERSION
com.pentaho|msg-box-info-assemblies=BASE_VERSION
com.pentaho|msg-box-info-plugins=BASE_VERSION
com.pentaho|msg-box-info-plugins-impl=BASE_VERSION
com.pentaho|msg-box-info-plugins-ui=BASE_VERSION
com.pentaho|mysql-bulk-loader=BASE_VERSION
com.pentaho|mysql-bulk-loader-assemblies=BASE_VERSION
com.pentaho|mysql-bulk-loader-impl=BASE_VERSION
com.pentaho|mysql-bulk-loader-plugins=BASE_VERSION
com.pentaho|mysql-bulk-loader-ui=BASE_VERSION
com.pentaho|oracle-bulk-loader=BASE_VERSION
com.pentaho|oracle-bulk-loader-assemblies=BASE_VERSION
com.pentaho|oracle-bulk-loader-plugins=BASE_VERSION
com.pentaho|oracle-bulk-loader-plugins-impl=BASE_VERSION
com.pentaho|oracle-bulk-loader-plugins-ui=BASE_VERSION
com.pentaho|palo=BASE_VERSION
com.pentaho|palo-assemblies=BASE_VERSION
com.pentaho|pdi-assemblies=BASE_VERSION
com.pentaho|pdi-avro-format-core=BASE_VERSION
com.pentaho|pdi-avro-format-plugin=BASE_VERSION
com.pentaho|pdi-ce=BASE_VERSION
com.pentaho|pdi-core=BASE_VERSION
com.pentaho|pdi-core-plugins=BASE_VERSION
com.pentaho|pdi-core-plugins-assemblies=BASE_VERSION
com.pentaho|pdi-core-plugins-impl=BASE_VERSION
com.pentaho|pdi-core-plugins-ui=BASE_VERSION
com.pentaho|pdi-engine-api=BASE_VERSION
com.pentaho|pdi-engine-configuration-api=BASE_VERSION
com.pentaho|pdi-engine-configuration-impl=BASE_VERSION
com.pentaho|pdi-engine-configuration-plugin=BASE_VERSION
com.pentaho|pdi-engine-ext=BASE_VERSION
com.pentaho|pdi-google-analytics-plugin=BASE_VERSION
com.pentaho|pdi-google-analytics-plugin-core=BASE_VERSION
com.pentaho|pdi-integration-tests=BASE_VERSION
com.pentaho|pdi-libs=BASE_VERSION
com.pentaho|pdi-pur-plugin=BASE_VERSION
com.pentaho|pdi-pur-plugin-core=BASE_VERSION
com.pentaho|pdi-salesforce-core=BASE_VERSION
com.pentaho|pdi-salesforce-plugin=BASE_VERSION
com.pentaho|pdi-samples=BASE_VERSION
com.pentaho|pdi-static=BASE_VERSION
com.pentaho|pdi-xml-plugin=BASE_VERSION
com.pentaho|pdi-xml-plugin-core=BASE_VERSION
com.pentaho|pentaho-googledrive-vfs=BASE_VERSION
com.pentaho|pentaho-googledrive-vfs-assemblies=BASE_VERSION
com.pentaho|pentaho-googledrive-vfs-core=BASE_VERSION
com.pentaho|pentaho-googledrive-vfs-plugin=BASE_VERSION
com.pentaho|pentaho-importer-utility=BASE_VERSION
com.pentaho|pentaho-importer-utility-assembly=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator-api=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator-assemblies=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator-core=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator-impl=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator-impl-platform=BASE_VERSION
com.pentaho|pentaho-kettle-repository-locator-impl-spoon=BASE_VERSION
com.pentaho|pentaho-metastore-locator-api=BASE_VERSION
com.pentaho|pentaho-metastore-locator-assemblies=BASE_VERSION
com.pentaho|pentaho-metastore-locator-core=BASE_VERSION
com.pentaho|pentaho-metastore-locator-plugin=BASE_VERSION
com.pentaho|pentaho-reporting=BASE_VERSION
com.pentaho|pentaho-reporting-assemblies=BASE_VERSION
com.pentaho|pentaho-reporting-plugins=BASE_VERSION
com.pentaho|pentaho-reporting-plugins-impl=BASE_VERSION
com.pentaho|pentaho-reporting-plugins-ui=BASE_VERSION
com.pentaho|pentaho-repository-vfs=BASE_VERSION
com.pentaho|pentaho-repository-vfs-assemblies=BASE_VERSION
com.pentaho|pentaho-repository-vfs-core=BASE_VERSION
com.pentaho|pentaho-repository-vfs-feature=BASE_VERSION
com.pentaho|pentaho-s3-vfs=BASE_VERSION
com.pentaho|pentaho-s3-vfs-plugin=BASE_VERSION
com.pentaho|pentaho-streaming=BASE_VERSION
com.pentaho|pentaho-streaming-assemblies=BASE_VERSION
com.pentaho|pentaho-streaming-impls=BASE_VERSION
com.pentaho|pentaho-streaming-jms-plugin=BASE_VERSION
com.pentaho|pentaho-streaming-jms-plugin-zip=BASE_VERSION
com.pentaho|pentaho-streaming-kafka-plugin=BASE_VERSION
com.pentaho|pentaho-streaming-mqtt-plugin=BASE_VERSION
com.pentaho|pentaho-streaming-mqtt-plugin-zip=BASE_VERSION
com.pentaho|postgresql-db-bulk-loader=BASE_VERSION
com.pentaho|postgresql-db-bulk-loader-assemblies=BASE_VERSION
com.pentaho|postgresql-db-bulk-loader-plugins=BASE_VERSION
com.pentaho|postgresql-db-bulk-loader-plugins-impl=BASE_VERSION
com.pentaho|postgresql-db-bulk-loader-plugins-ui=BASE_VERSION
com.pentaho|pur=BASE_VERSION
com.pentaho|pur-assemblies=BASE_VERSION
com.pentaho|put-a-file-with-ftp=BASE_VERSION
com.pentaho|put-a-file-with-ftp-assemblies=BASE_VERSION
com.pentaho|put-a-file-with-ftp-plugins=BASE_VERSION
com.pentaho|put-a-file-with-ftp-plugins-impl=BASE_VERSION
com.pentaho|put-a-file-with-ftp-plugins-ui=BASE_VERSION
com.pentaho|put-file-sftp=BASE_VERSION
com.pentaho|put-file-sftp-assemblies=BASE_VERSION
com.pentaho|put-file-sftp-plugins=BASE_VERSION
com.pentaho|put-file-sftp-plugins-impl=BASE_VERSION
com.pentaho|put-file-sftp-plugins-ui=BASE_VERSION
com.pentaho|random-cc-number-generator=BASE_VERSION
com.pentaho|random-cc-number-generator-assemblies=BASE_VERSION
com.pentaho|random-cc-number-generator-plugins=BASE_VERSION
com.pentaho|random-cc-number-generator-plugins-impl=BASE_VERSION
com.pentaho|random-cc-number-generator-plugins-ui=BASE_VERSION
com.pentaho|repo-vfs-pdi=BASE_VERSION
com.pentaho|repo-vfs-plugin=BASE_VERSION
com.pentaho|repo-vfs-plugin-assemblies=BASE_VERSION
com.pentaho|repo-vfs-plugin-assembly=BASE_VERSION
com.pentaho|repo-vfs-pur=BASE_VERSION
com.pentaho|repo-vfs-ws=BASE_VERSION
com.pentaho|repositories=BASE_VERSION
com.pentaho|repositories-assemblies=BASE_VERSION
com.pentaho|repositories-plugin=BASE_VERSION
com.pentaho|repositories-plugin-core=BASE_VERSION
com.pentaho|repository-proxy=BASE_VERSION
com.pentaho|rest=BASE_VERSION
com.pentaho|rest-assemblies=BASE_VERSION
com.pentaho|rest-core=BASE_VERSION
com.pentaho|rss=BASE_VERSION
com.pentaho|rss-assemblies=BASE_VERSION
com.pentaho|rss-plugins=BASE_VERSION
com.pentaho|rss-plugins-impl=BASE_VERSION
com.pentaho|rss-plugins-ui=BASE_VERSION
com.pentaho|s3-vfs=BASE_VERSION
com.pentaho|s3csvinput=BASE_VERSION
com.pentaho|s3csvinput-assemblies=BASE_VERSION
com.pentaho|salesforce=BASE_VERSION
com.pentaho|salesforce-assemblies=BASE_VERSION
com.pentaho|sap=BASE_VERSION
com.pentaho|sap-assemblies=BASE_VERSION
com.pentaho|server-vfs-test-plugin=BASE_VERSION
com.pentaho|sftpput=BASE_VERSION
com.pentaho|sftpput-assemblies=BASE_VERSION
com.pentaho|sftpput-plugin=BASE_VERSION
com.pentaho|sftpput-plugin-impl=BASE_VERSION
com.pentaho|sftpput-plugin-ui=BASE_VERSION
com.pentaho|shapefilereader=BASE_VERSION
com.pentaho|shapefilereader-assemblies=BASE_VERSION
com.pentaho|terafast-bulk-loader=BASE_VERSION
com.pentaho|terafast-bulk-loader-assemblies=BASE_VERSION
com.pentaho|terafast-bulk-loader-plugins=BASE_VERSION
com.pentaho|terafast-bulk-loader-plugins-impl=BASE_VERSION
com.pentaho|terafast-bulk-loader-plugins-ui=BASE_VERSION
com.pentaho|vfs-test-plugin-server-assembly=BASE_VERSION
com.pentaho|xml=BASE_VERSION
com.pentaho|xml-assemblies=BASE_VERSION
com.pentaho|yaml-input-assemblies=BASE_VERSION
com.pentaho|yaml-input-plugins=BASE_VERSION
com.pentaho|yaml-input-plugins-impl=BASE_VERSION
encryption-support.version=[11.1.0.0-1,11.1.0.0-999]
vertica-bulkloader-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-reporting-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pdi-platform-utils-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-metaverse.version=[11.1.0.0-1,11.1.0.0-999]
org.pentaho|pentaho-ce-bundle-parent-pom=[11.1.0.0-1,11.1.0.0-999]
pdi-sap-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-mongodb-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pdi-json-plugin.version=[11.1.0.0-1,11.1.0.0-999]
org.pentaho|pentaho-ce-jar-parent-pom=[11.1.0.0-1,11.1.0.0-999]
metastore.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-hadoop-shims.version=[11.1.0.0-1,11.1.0.0-999]
platform.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-vfs-browser.version=[11.1.0.0-1,11.1.0.0-999]
pdi.version=[11.1.0.0-1,11.1.0.0-999]
pdi-rest-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pdi-salesforce-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-osgi-bundles.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-karaf.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-json.version=[11.1.0.0-1,11.1.0.0-999]
commons-database.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-connections.version=[11.1.0.0-1,11.1.0.0-999]
mondrian.version=[11.1.0.0-1,11.1.0.0-999]
pdi-osgi-bridge.version=[11.1.0.0-1,11.1.0.0-999]
pdi-pur-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-metadata.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-registry.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-launcher.version=[11.1.0.0-1,11.1.0.0-999]
oss-licenses.version=[11.1.0.0-1,11.1.0.0-999]
pdi-xml-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-reporting.version=[11.1.0.0-1,11.1.0.0-999]
commons-xul.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-metastore.version=[11.1.0.0-1,11.1.0.0-999]
big-data-plugin.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-capability-manager.version=[11.1.0.0-1,11.1.0.0-999]
pentaho-i18n-bundle.version=[11.1.0.0-1,11.1.0.0-999]