package org.pentaho.di.core.database;

import org.junit.Before;
import org.junit.Test;
import org.pentaho.di.core.row.ValueMetaInterface;

import java.sql.ResultSetMetaData;

import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;

public class BaseDatabaseMetaTest {
  private BaseDatabaseMeta baseDatabaseMeta;
  

  @Before 
  public void setUp() throws Exception {
    baseDatabaseMeta = new GenericDatabaseMeta();
  }

  @Test
  public void testGetSequenceNoMaxValueOption() throws Exception {
    assertEquals( "NOMAXVALUE", baseDatabaseMeta.getSequenceNoMaxValueOption() );
  }
  
  @Test 
  public void testSupportsAutoGeneratedKeys() throws Exception {
    assertTrue( baseDatabaseMeta.supportsAutoGeneratedKeys() );
  }

  @Test 
  public void testCustomizeValueFromSQLType() throws Exception {
    assertNull( baseDatabaseMeta.customizeValueFromSQLType( mock( ValueMetaInterface.class ),
        mock( ResultSetMetaData.class ), 1 ) );
  }
}
