/*this will enable strict sql mode.*/
SET PROPERTY "sql.enforce_strict_size" TRUE;
/*for 1st case (negative)*/
DROP TABLE LOG_JOB_TEST15 IF EXISTS;
CREATE memory TABLE LOG_JOB_TEST15
(ID_JOB INTEGER, CHANNEL_ID VARCHAR(255), JOBNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT,LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD CHAR(10));
/*for 1st case (positive)*/
DROP TABLE LOG_JOB_TEST15_CLOB IF EXISTS;
CREATE memory TABLE LOG_JOB_TEST15_CLOB
(ID_JOB INTEGER, CHANNEL_ID LONGVARCHAR, JOBNAME VARCHAR(255), STATUS LONGVARCHAR, LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT,LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD LONGVARCHAR);
/*for 2nd case*/
DROP TABLE LOG_JOB_TEST255 IF EXISTS;
CREATE memory TABLE LOG_JOB_TEST255
(ID_JOB INTEGER, CHANNEL_ID VARCHAR(255), JOBNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT,LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(255));
/* for log table defined inside transaction */
DROP TABLE LOG_TRANS_TEST15 IF EXISTS;
CREATE memory TABLE LOG_TRANS_TEST15 ( ID_BATCH INTEGER, CHANNEL_ID VARCHAR(255), TRANSNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT, LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(15));
/* for log transformation */
DROP TABLE LOG_TRANS_TEST2000 IF EXISTS;
CREATE memory TABLE LOG_TRANS_TEST2000 (ID_BATCH INTEGER, CHANNEL_ID VARCHAR(255), TRANSNAME VARCHAR(255), STATUS VARCHAR(15), LINES_READ BIGINT, LINES_WRITTEN BIGINT, LINES_UPDATED BIGINT, LINES_INPUT BIGINT, LINES_OUTPUT BIGINT, LINES_REJECTED BIGINT, ERRORS BIGINT, STARTDATE TIMESTAMP, ENDDATE TIMESTAMP, LOGDATE TIMESTAMP, DEPDATE TIMESTAMP, REPLAYDATE TIMESTAMP, LOG_FIELD VARCHAR(2000));