FROM ubuntu:18.04

ENV PHANTOMJS_VERSION 2.1.1

RUN apt-get update -qq && \
    apt-get -qy install ca-certificates rsync curl libfontconfig python python-pip python-setuptools && \
    curl -SL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 | tar xj -C /usr/local --strip-components=1 && \
    pip install dockerize

ADD pack_libs.sh /

CMD ["sh", "-c", "/pack_libs.sh"]